FROM ubuntu:20.04
MAINTAINER  <Dimitis Vagiakakos> <dimitrislinuxos@protonmail.ch>
RUN apt update 
RUN apt install -y pip python3-pip
RUN pip install flask pymongo bson
RUN mkdir /app
RUN mkdir -p /app/data
COPY service.py /app/service.py
ADD data /app/data
EXPOSE 5000
WORKDIR /app
ENTRYPOINT ["python3","-u","service.py" ]

